---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.php"
rulesets: "cleancode,codesize,controversial,design,unusedcode,naming,.codecllimate.ruleset.xml"
exclude_paths:
- test/
- vendor/