language: php
php:
  - 7.0
  - 7.1
sudo: false
cache:
  directories:
  - vendor
  
before_install:
  - composer update
  - composer require satooshi/php-coveralls
install:
  - travis_retry composer install --no-interaction --prefer-source
script:
  - vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml
after_script:
  - php vendor/bin/coveralls -v
branches:
  only:
    - master
after_success:
  - coveralls